name: publish

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Build (x86)
      run: dotnet publish -p:PublishProfile=x86
      working-directory: ./src
    - name: Build (x64)
      run: dotnet publish -p:PublishProfile=x64
      working-directory: ./src
    - name: Upload artifact (x86)
      uses: actions/upload-artifact@v3
      with:
        name: x86
        path: ./src/bin/Release/net6.0-windows/publish/win-x86/AudioStream.exe
    - name: Upload artifact (x64)
      uses: actions/upload-artifact@v3
      with:
        name: x64
        path: ./src/bin/Release/net6.0-windows/publish/win-x64/AudioStream.exe
    - name: Upload release asset (x86)
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./src/bin/Release/net6.0-windows/publish/win-x86/AudioStream.exe
        asset_name: AudioStream-x86.exe
    - name: Upload release asset (x64)
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./src/bin/Release/net6.0-windows/publish/win-x64/AudioStream.exe
        asset_name: AudioStream-x64.exe
